name: CI

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install xorg-dev libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev libc6
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        sh reset.sh
        export FLASK_APP=FlowerEvolver.py
        export LD_LIBRARY_PATH=./bin:$LD_LIBRARY_PATH
        sudo chmod +x bin/*
        python -m pytest

    - name: Run Lint
      run: |
        python -m flake8 --per-file-ignores='app/__init__.py:F401'
